#!/bin/sh

COMMAND=$1

function newPost() {
    test -d .venv || python -m virtualenv .venv
    . .venv/bin/activate
    pip install -q python-slugify
    slug=$(python -c "from slugify import slugify; print(slugify('$1'))")
    post="$(date +"./content/blog/%Y-%m-%d-${slug}.md")"
    if [ -f $post ] ; then
        echo "Post already exists!"
        exit 1
    fi
    cat > $post <<EOF
+++
title = "$1"
+++
EOF
    echo $post
}

case $COMMAND in
    "build") zola build -o docs ;;
    "new-post") newPost "$2" ;;
    *)
        dir=$(mktemp -d)
        trap "rm -Rf $dir" EXIT
        zola serve --drafts -o $dir
        ;;
esac
